### ISSUE TITLE
Missing possible important feature "SECURITY DEFINER" in #[pg_extern]

### ISSUE THREAD

**Issue by davidoabile** [tcdi/pgrx#1064]
Why do we need it? If you have roles, and let's say you have an anonymous user to whom users will be auto-assigned until they login, and then switch to their role, the anon user may need to call the login function, which accesses private schemas, e.g. auth. Users with a read and write. While it is possible to write this function in PG UDF, it is safer to write it in rust to hide code from some DB admin.  

We can add the Security Definer by hand to the generated function but it will be good to include it in the source. Unless, I missed the process

**Comment by workingjubilee** [comment]
"hide code from some DB admin"?

I am not sure what you mean?

**Comment by davidoabile** [comment]
How do you create a function like the below in pgx?
CREATE OR REPLACE FUNCTION signup(
	email text,
	password text
)
    RETURNS text
    LANGUAGE 'plpgsql'
    VOLATILE SECURITY DEFINER UNSAFE
AS $BODY$
......

Who do we add SECURITY DEFINER in the pg_extern macro?
