### ISSUE TITLE
Performance overhead when performing array calculations

### ISSUE THREAD

**Issue by jkatz** [tcdi/pgrx#1086]
Related issue: https://github.com/tcdi/plrust/issues/275

There is some performance overhead when performing calculations on arrays compared to C, which is particularly noticeable on higher-dimensional arrays. The tests were carried out on PL/Rust, but per https://github.com/tcdi/plrust/issues/275#issuecomment-1489187564 this is related to how pgx extracts data from PostgreSQL arrays.

I don't have pgx-specific examples, but the PL/Rust examples are in https://github.com/tcdi/plrust/issues/275

**Comment by eeeebbbbrrrr** [comment]
This should be resolved in the forthcoming pgrx 0.8.0 release.  Work on plrust to integrate the new zero-copy Array support hasn't begun yet.
