### ISSUE TITLE
Support for library with different name than crate name

### ISSUE THREAD

**Issue by azam** [tcdi/pgrx#1099]
An extension I am writing is part of multiple projects that have the same prefix, but for different purposes. As such, the crate name and the output binary may not be the same, configured at Cargo.toml. We would get the below error when doing `cargo pgx run` for these kind of crates.

```
Error: 
   0: Could not get shared object file from Cargo output.

Location:
   /Users/azam/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.7.4/src/command/install.rs:384

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: cargo_pgx::command::install::find_library_file
      at /Users/azam/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.7.4/src/command/install.rs:351
   1: cargo_pgx::command::install::install_extension with pg_version=13.10 profile=Dev test=false features=["pg13"]
      at /Users/azam/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.7.4/src/command/install.rs:94
   2: cargo_pgx::command::run::run with pg_version=13.10 profile=Dev
      at /Users/azam/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.7.4/src/command/run.rs:94
   3: cargo_pgx::command::run::execute
      at /Users/azam/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-pgx-0.7.4/src/command/run.rs:55

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

The problem can be reproduced using any of the examples on this repo [(e.g. for strings)](https://github.com/tcdi/pgx/blob/master/pgx-examples/strings/Cargo.toml), by overriding the library name on the manifest as follows:

from:
```toml
[package]
name = "strings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
```

to:
```toml
[package]
name = "strings-pgx"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "strings"
```

A crate can only have one library, but the library does not necessarily be the crate name. Cargo manifest doc [here](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#library) does not explicitly say that, but under `[lib]` we can specify a `name` property that overrides the default library name, which is the crate name.

Seems like the function that finds the library file [(here)](https://github.com/tcdi/pgx/blob/f7ca21c4bf2028b5a17e009f2557864537e8f1d4/cargo-pgx/src/command/install.rs#L352) based on crate name. The function already have a reference to the whole manifest, could you add support for overridden library name as well?

**Comment by eeeebbbbrrrr** [comment]
This sounds like a reasonable ask.  Would you like to submit a PR?  We'd be happy to review it, merge it, and get it included in the next release.
