### ISSUE TITLE
Problem with custom indexes. 

### ISSUE THREAD

**Issue by karajan1001** [tcdi/pgrx#1136]
Hello, team. I have some questions about creating custom indexes with pgrx. Going through the issues in pgrx, I noticed that two years ago in #271  you said there is no simple solution and suggested implementing this in C. I want to know:
1. is this still the case in 2023?
2. What is the main difficulty of implementing a custom index with `Rust`?
3. Any probability of making pgrx support custom index-related functionalities?

Thank you

**Comment by eeeebbbbrrrr** [comment]
It's not that implementing the Index Access Method API is impossible or anything.  @zombodb is an example of that.

The difficulty is just that we don't have safe Rust wrappers around the API, let alone all the buffer management internals.  As such, you'll be spending a lot of time in `unsafe {}`.

Even so, I'd still have to say that using pgrx to implement the API is a far superior approach to doing it in C.  Rust provides so many benefits.

If you head down this road we're happy to try and answer any questions as you go along.  I've personally implemented the API a number of times both with pgrx and C, so I have a pretty solid understanding of it.

**Comment by karajan1001** [comment]
Thank you @eeeebbbbrrrr .

**Comment by karajan1001** [comment]
Hello, @eeeebbbbrrrr Excuse me. My first attempt is to implement a dummy_index_am with pgrx. following [The official example](https://github.com/postgres/postgres/blob/master/src/test/modules/dummy_index_am/dummy_index_am.c)
I create a rust version of it with `pgrx` the code in https://github.com/karajan1001/dummy_index_am.
It can be compiled but when I use `cargo pgrx run` and want to create the extension I got
```
dummy_index_am=# create extension dummy_index_am;
ERROR:  unsafe use of pseudo-type "internal"
DETAIL:  A result of type internal requires at least one input of type internal.
```

I'm sorry but I have no idea where the problem comes from. And how to debug this kind of problem.

**Comment by karajan1001** [comment]
Hello, @eeeebbbbrrrr Excuse me. My first attempt is to implement a dummy_index_am with pgrx. following [The official example](https://github.com/postgres/postgres/blob/master/src/test/modules/dummy_index_am/dummy_index_am.c)
I create a rust version of it with pgrx the code in https://github.com/karajan1001/dummy_index_am.
It can be compiled but when I use cargo pgrx run and want to create the extension I got

```
dummy_index_am=# create extension dummy_index_am;
ERROR:  unsafe use of pseudo-type "internal"
DETAIL:  A result of type internal requires at least one input of type internal.
```

According to the index access method chapter in the Postgres' official documents. I found

> An index access method handler function must be declared to accept a single argument of type internal and to return the pseudo-type index_am_handler. 

I guess the problem comes from the wrong input argument here but have no idea how to handle this. I just follow the example in C and use `pg_sys::FunctionCallInfo` as the input argument. 

Another question is that in most examples, they provide an initialization function
```
void _PG_init(void) {
}
```

Are there any alternatives in pgrx?

Thank you.

**Comment by eeeebbbbrrrr** [comment]
For the `amhandler` function (https://github.com/karajan1001/dummy_index_am/blob/dc50d26e434cfaedd1d810310e13875730f40459/src/lib.rs#L29), you need to write the SQL manually.  ZomboDB has an example of this at: https://github.com/zombodb/zombodb/blob/0468fc09f97fe9c8be3b947b138e37efce4c4d66/src/access_method/mod.rs#L11  It also creates the "ACCESS METHOD" object there too.

for `_PG_init()`, ZDB has an example of that too: https://github.com/zombodb/zombodb/blob/0468fc09f97fe9c8be3b947b138e37efce4c4d66/src/lib.rs#L50  Don't forget the `#[pg_guard]`!

**Comment by karajan1001** [comment]
> ACCESS METHOD



> For the `amhandler` function (https://github.com/karajan1001/dummy_index_am/blob/dc50d26e434cfaedd1d810310e13875730f40459/src/lib.rs#L29), you need to write the SQL manually. ZomboDB has an example of this at: https://github.com/zombodb/zombodb/blob/0468fc09f97fe9c8be3b947b138e37efce4c4d66/src/access_method/mod.rs#L11 It also creates the "ACCESS METHOD" object there too.
> 


Thank you @eeeebbbbrrrr , Yes,  I just wondered why does this `sql` required here. Because according to the related `C` code, you need to create an external function and introduce it in the Postgres interface with the SQL command added here.
